config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our flats</h1>

<div class="flats-list">
  <% @flats.each do |flat| %>
      <%= link_to flat_path(flat), class:'flat-link' do %>
        <div class="flat-card">
          <%= image_tag "image.jpg", alt: "flat", class: "flat-card-image"%>
          <h4><%= flat.name %></h4>
          <p><%= flat.address %></p>
          <p><%= flat.number_of_guests %> </p>
          <p><%= flat.price_per_night %> </p>
        </div>
      <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <form class="form-inline">
      <button class="btn btn-outline-success" type="button">Add Flat</button>
  </form>
    </nav>
    <%= yield %>
  </body>
</html>